version: '3.8'

services:

#  mysqldb:
#    image: mysql:8.0
#    restart: always
#    environment:
#      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_DATABASE: mediquiz
#      MYSQL_PASSWORD: 1234
#    volumes:
#      - db_data:/var/lib/mysql

  web:
    image: mediserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    depends_on:
#      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://5.tcp.eu.ngrok.io:19457/mediquiz
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: {}