version: "3.8"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring-mysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/mediquiz?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3306"
    networks:
      - spring-mysql-net
    environment:
      MYSQL_DATABASE: mediquiz
      MYSQL_USER: jeka
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234

networks:
  spring-mysql-net:
