spring:
  datasource:
    password: 1234
    url: jdbc:mysql://db:3307/mediquiz
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  flyway:
    url: jdbc:mysql://db:3307/mediquiz
    user: root
    password: 1234
    schemas: mediquiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    enabled: true

  data:
    mongodb:
      uri: mongodb+srv://admin:mEGNzra5oQRlvhTB@mediquiz.1bdifvh.mongodb.net/MediQuiz?retryWrites=true&w=majority&maxIdleTimeMS=60000

server:
  error:
    include-message: always